FROM alpine:3

LABEL author="Helmi Nadilla Yahya"
LABEL company="Restofy" website="https://helmiyahyaa.github.io/"

RUN mkdir hello
RUN echo "Hello World" > "hello/world.txt"

CMD cat "hello/world.txt"